### ISSUE TITLE
Scanner fails after reboot

### ISSUE THREAD

**Issue by agrrajag** [yu210148/gvm_install#1]
The install worked great... took a little over two hours. After I got it on and ran a test, I did a reboot of the machine. After the reboot, the scanner is not able to load and is giving me a Failure to verify scanner.

**Comment by yu210148** [comment]
Humm, 

Where are you seeing that? On the command line or in the web interface?

Kev.

**Comment by yu210148** [comment]
Just fired mine up and tried doing the verify scanner step from the guide (https://kifarunix.com/install-and-setup-gvm-11-on-ubuntu-20-04/) as the gvm user at the command line and got the same thing. 

I suspect it's related to the 'failed to connect to /opt/gvm/var/run/ospd.sock' messages showing up in /opt/gvm/var/log/gvm/gvmd.log that's described in the comments there which I'm also now getting. 

I'm not sure what the fix is at this time but I'll update this if I come up with a solution.

kev.

**Comment by agrrajag** [comment]
I am seeing it on both... If I go to the scanners menu and verify the
created one, it says scanner unavailable.

If I go sudo su - gvm, get scanners, and verify, it says unable to verify
scanner.

**Comment by ankush-grover-3pg** [comment]
One of the reason is ospd-openvas.pid and ospd.sock does not gets deleted from /opt/gvm/var/run after you reboot the system. The ospd-openvas complains that another process is already running. What I did, deleted both ospd-openvas.pid & ospd.sock files, rebooted the system and after reboot both gvmd & ospd-openvas started working fine. Now the issue I am facing is that gsad is not coming up on the browser. Will troubleshoot gsad further.

**Comment by yu210148** [comment]
Wow, cool. I guess I could work out a way to have this script put something in to automatically remove those files when the system is shut down. I'll have to do some Googling to see what all gets called when shutdown is invoked and see if there's somewhere I could put a script to remove those files.

**Comment by congacon28102020** [comment]
> The reason is ospd-openvas.pid and ospd.sock does not gets deleted from /opt/gvm/var/run after you reboot the system. The ospd-openvas complains that another process is already running. What I did, deleted both ospd-openvas.pid & ospd.sock files, rebooted the system and after reboot both gvmd & ospd-openvas started working fine.

I have deleted the both of ospd-openvas.pid & ospd.sock files but still not access GVM via portal.

**Comment by congacon28102020** [comment]
> Wow, cool. I guess I could work out a way to have this script put something in to automatically remove those files when the system is shut down. I'll have to do some Googling to see what all gets called when shutdown is invoked and see if there's somewhere I could put a script to remove those files.

Hi yu210148,

Does script updated?

**Comment by xenago** [comment]
From a comment on the linked page:

[Link](https://kifarunix.com/install-and-setup-gvm-11-on-ubuntu-20-04/#comment-12864
)
> I’ve got a fix for this. The issue is that not all of the runtime files are cleaned up properly on exit. If these runtime files exist the scanner fails to launch properly. To resolve the issue in the openvas.service file insert the line:
> 
> ExecStartPre=-rm /opt/gvm/var/run/ospd-openvas.pid /opt/gvm/var/run/ospd.sock /opt/gvm/var/run/gvmd.sock
> 
> This will delete the files if they exist and allow the service to come up cleanly after a server restart.


Hope this helps!

**Comment by yu210148** [comment]
Sweet, thanks xenago. I've merged it in. :)

**Comment by DownRightFPV** [comment]
I'm still having this issue... I've confirmed that `ExecStartPre=-rm /opt/gvm/var/run/ospd-openvas.pid /opt/gvm/var/run/ospd.sock /opt/gvm/var/run/gvmd.sock` is present in openvas.service.  

I've also tried manually deleting the files, and rebooting, but no luck.  Any help is greatly appreciated

**Comment by xenago** [comment]
I found a solution to this new problem which should help. I submitted a PR to add the changes to the script:

https://github.com/yu210148/gvm_install/pull/6

Seems like the NVTs take a long time to load on startup, so the socket wasn't open for gvm and then gsa. The solution for your existing installation should be to create two path files and reload.

The first:

```
root@vm:/home/user# cat /etc/systemd/system/gvm.path
[Unit]
Description=Monitor for opsd.sock to start gvm

[Path]
PathChanged=/opt/gvm/var/run/ospd.sock
Unit=gvm.service

[Install]
WantedBy=multi-user.target
```
The second:
```
root@vm:/home/user# cat /etc/systemd/system/gsa.path
[Unit]
Description=Monitor for gvmd.sock

[Path]
PathChanged=/opt/gvm/var/run/gvmd.sock
Unit=gsa.service

[Install]
WantedBy=multi-user.target
```

Then reload and reboot and it should work as expected:
```
sudo systemctl daemon-reload
sudo systemctl enable gvm.{path,service}
sudo systemctl enable gsa.{path,service}

```

Hope this helps!

**Comment by DownRightFPV** [comment]
Thank you for the quick reply @xenago 

I've done as you suggested, and have verified the scanner, (this time successfully), however, I'm still receiving the error "Could not connect to Scanner".

**Comment by DownRightFPV** [comment]
OK, I think I've figured it out... the new task wizard uses the OpenVAS Default scanner and not the "Created OpenVAS Scanner".  Running the task via "new task" allows me to select the scanner, and that seems to be working properly.

I also attempted to verify the "OpenVAS Default" scanner, but I just get "Service Unavailable".

Is it possible to set "Created OpenVAS Scanner" as the default so the new task wizard is usable?

Thanks again for the help

**Comment by xenago** [comment]
Yeah, that's noted in the README of the github, it's normal.

And no idea about the default, sorry, what do you mean by 'usable'? I just select the Created scanner and it works fine.

**Comment by yu210148** [comment]
Yes, the walkthrough it's based on uses that created scanner rather than
the default.

Kev.

**Comment by DownRightFPV** [comment]
Thanks again @xenago and @yu210148 and apologies for missing that comment in the README

**Comment by xenago** [comment]
DownRight, I believe it is possible to do by going to your User settings for your account in GVM and editing the default scanner!

**Comment by DownRightFPV** [comment]
Hey you're right!  Thanks!
